export type GameId='cardfall'|'blackjack'|'holdem'|'solitaire'|'highcard';
export type GameField={key:string;label:string;type:'number'|'select'|'toggle';help:string;options?:Array<{label:string;value:string|number|boolean}>;min?:number;max?:number};
export type GameDefinition={id:GameId;name:string;tagline:string;players:string;accent:string;rules:string[];fields:GameField[];settings:Record<string,string|number|boolean>};
export const GAME_CATALOG:GameDefinition[]=[
 {id:'cardfall',name:'Cardfall',tagline:'Ask. Guess. Topple the hand.',players:'2–8 players',accent:'gold',rules:['Each player receives hidden cards.','On your turn, ask a Yes/No question or guess one exact card.','The last player with cards remaining wins.'],fields:[{key:'cardsPerPlayer',label:'Cards per player',type:'number',min:1,max:10,help:'Default is five cards.'},{key:'timer',label:'Turn timer',type:'select',options:[{label:'No timer',value:'off'},{label:'30 seconds',value:'30'},{label:'60 seconds',value:'60'}],help:'Unanswered turns can auto-pass.'}],settings:{cardsPerPlayer:5,timer:'off'}},
 {id:'blackjack',name:'Blackjack',tagline:'Beat the dealer. Get close to 21.',players:'1–5 players',accent:'red',rules:['Get closer to 21 than the dealer without going over.','Face cards count as ten; Aces count as one or eleven.','Hit for another card or stand on your hand.'],fields:[{key:'players',label:'Seats',type:'number',min:1,max:5,help:'Guests can join until the table is full.'},{key:'dealerSoft17',label:'Dealer on soft 17',type:'select',options:[{label:'Dealer stands',value:'stand'},{label:'Dealer hits',value:'hit'}],help:'Choose the house rule.'}],settings:{players:5,dealerSoft17:'stand'}},
 {id:'holdem',name:'Texas Hold’em',tagline:'Read the table. Play the hand.',players:'2–8 players',accent:'blue',rules:['Each player receives two private hole cards.','Five community cards are revealed across the flop, turn, and river.','Make the best five-card hand from all available cards.'],fields:[{key:'players',label:'Seats',type:'number',min:2,max:8,help:'Play with friends around one table.'},{key:'startingChips',label:'Starting chips',type:'select',options:[{label:'1,000 chips',value:'1000'},{label:'5,000 chips',value:'5000'}],help:'Play money only.'}],settings:{players:6,startingChips:'1000'}},
 {id:'solitaire',name:'Solitaire',tagline:'A quiet classic, just for you.',players:'1 player',accent:'purple',rules:['Build four foundation piles from Ace through King.','Move cards between tableau columns in alternating colors.','Turn through the stock and clear the tableau.'],fields:[{key:'variant',label:'Variant',type:'select',options:[{label:'Klondike draw 1',value:'draw1'},{label:'Klondike draw 3',value:'draw3'}],help:'Draw one or three cards from the stock.'}],settings:{variant:'draw1'}},
 {id:'highcard',name:'High Card Duel',tagline:'Reveal together. Highest card wins.',players:'2–8 players',accent:'green',rules:['Everyone receives one hidden card.','Reveal at the same time.','The highest rank wins the round.'],fields:[{key:'players',label:'Seats',type:'number',min:2,max:8,help:'Invite friends or start when ready.'}],settings:{players:4}}
];
export function gameById(id:GameId){return GAME_CATALOG.find(g=>g.id===id)!}
export function defaultSettings(id:GameId){return {...gameById(id).settings}}
export function normalizeSettings(id:GameId,input:Record<string,unknown>){const game=gameById(id);const out=defaultSettings(id);for(const field of game.fields){const value=input[field.key];if(field.type==='number'&&typeof value==='number'){if(value<field.min!)out[field.key]=field.min!;else if(value<=field.max!)out[field.key]=value};if(field.type!=='number'&&field.options?.some(o=>o.value===value))out[field.key]=value as string|boolean}return out}
