import type { Card } from '../cards/deck';
import { createDeck, shuffle } from '../cards/deck';
import { createBlackjack, handValue, hit as blackjackHit, stand as blackjackStand, type BlackjackState } from './blackjack/engine';
import { dealHoldem } from './holdem/engine';
import { dealHighCard } from './high-card/engine';
import type { GameId } from './catalog';

export type RuntimeGameId=Exclude<GameId,'cardfall'>;
export type RuntimePlayer={id:string;name:string;hand:Card[];removed:Card[];correctGuesses:number;stood?:boolean;revealed?:boolean;chips?:number};
export type RuntimeState={gameId:RuntimeGameId;phase:'lobby'|'playing'|'finished';players:RuntimePlayer[];turn:number;events:{id:string;text:string;tone?:string}[];settings:Record<string,string|number|boolean>;deck:Card[];stock:Card[];waste:Card[];tableau:Card[][];dealer?:{hand:Card[];revealed:boolean};community:Card[];street?:'preflop'|'flop'|'turn'|'river'|'showdown';checked:Record<string,boolean>;winner?:string;revealedCards:Record<string,boolean>;results?:Record<string,string>};
export type RuntimeAction={type:'START'|'HIT'|'STAND'|'DRAW'|'REVEAL'|'CHECK';actorId:string;seed?:number};
const uid=()=>globalThis.crypto?.randomUUID?.()??`event-${Date.now()}-${Math.random()}`;
const event=(text:string,tone?:string)=>({id:uid(),text,tone});
const clone=<T>(value:T):T=>structuredClone(value);
const rankValue=(rank:string)=>rank==='A'?14:['K','Q','J'].includes(rank)?({K:13,Q:12,J:11} as Record<string,number>)[rank]:Number(rank);
const nextActive=(s:RuntimeState,from:number)=>{for(let step=1;step<=s.players.length;step++){const index=(from+step)%s.players.length;const p=s.players[index];if(!p.stood&&p.hand.length>0)return index;}return from;};

export function createLobby(gameId:RuntimeGameId,settings:Record<string,string|number|boolean>):RuntimeState{return{gameId,phase:'lobby',players:[],turn:0,events:[],settings,deck:[],stock:[],waste:[],tableau:[],community:[],checked:{},revealedCards:{}};}
export function addPlayer(state:RuntimeState,player:Pick<RuntimePlayer,'id'|'name'>):RuntimeState{if(state.phase!=='lobby')throw Error('This game has already started');if(state.players.some(p=>p.id===player.id))return state;const max=state.gameId==='blackjack'?5:state.gameId==='solitaire'?1:8;if(state.players.length>=max)throw Error('Room is full');return{...state,players:[...state.players,{...player,hand:[],removed:[],correctGuesses:0}]};}
function startBlackjack(s:RuntimeState,seed:number):RuntimeState{const bj=createBlackjack(s.players.map(p=>p.id),seed);return{...s,phase:'playing',turn:0,deck:bj.deck,dealer:bj.dealer,players:s.players.map(p=>({...p,hand:bj.players[p.id].hand,stood:false})),events:[...s.events,event('The dealer dealt two cards to every player.','deal')]};}
function startHoldem(s:RuntimeState,seed:number):RuntimeState{const hand=dealHoldem(s.players.map(p=>p.id),seed);return{...s,phase:'playing',turn:0,deck:[],community:hand.community,street:'preflop',players:s.players.map(p=>({...p,hand:hand.holes[p.id],chips:Number(s.settings.startingChips??1000)})),events:[...s.events,event('The table dealt two private hole cards.','deal')]};}
function startSolitaire(s:RuntimeState,seed:number):RuntimeState{const d=shuffle(createDeck(),seed);const tableau:Card[][]=[];let cursor=0;for(let column=0;column<7;column++){tableau.push(d.slice(cursor,cursor+column+1));cursor+=column+1;}return{...s,phase:'playing',turn:0,tableau,stock:d.slice(cursor),waste:[],players:s.players.map(p=>({...p,hand:[]})),events:[...s.events,event('Solitaire is ready. Build the foundations from Ace to King.','deal')]};}
function startHighCard(s:RuntimeState,seed:number):RuntimeState{const hand=dealHighCard(s.players.map(p=>p.id),seed);return{...s,phase:'playing',turn:0,players:s.players.map(p=>({...p,hand:[hand.cards[p.id]],revealed:false})),revealedCards:{},events:[...s.events,event('Everyone received one hidden card. Reveal when ready.','deal')]};}
export function reduceRuntime(state:RuntimeState,action:RuntimeAction):RuntimeState{const s=clone(state);if(action.type==='START'){if(s.phase!=='lobby')throw Error('Game has already started');const minimum=s.gameId==='solitaire'||s.gameId==='blackjack'?1:2;if(s.players.length<minimum)throw Error(`Need at least ${minimum} player${minimum===1?'':'s'}`);if(s.gameId==='blackjack')return startBlackjack(s,action.seed??1);if(s.gameId==='holdem')return startHoldem(s,action.seed??1);if(s.gameId==='solitaire')return startSolitaire(s,action.seed??1);return startHighCard(s,action.seed??1);}
if(s.phase!=='playing')throw Error('Game is not active');const actor=s.players[s.turn];if(!actor||actor.id!==action.actorId)throw Error('Not your turn');
if(s.gameId==='blackjack'&&(action.type==='HIT'||action.type==='STAND')){const source:BlackjackState={phase:s.phase,players:Object.fromEntries(s.players.map(p=>[p.id,{hand:p.hand,stood:Boolean(p.stood)}])),dealer:s.dealer!,deck:s.deck};const next=action.type==='HIT'?blackjackHit(source,actor.id):blackjackStand(source,actor.id);const players=s.players.map(p=>({...p,hand:next.players[p.id].hand,stood:next.players[p.id].stood}));if(next.phase==='finished')return{...s,phase:'finished',players,deck:next.deck,dealer:next.dealer,results:next.results,events:[...s.events,event('The dealer revealed the final hand.','win')]};const turn=nextActive({...s,players},s.turn);return{...s,players,deck:next.deck,dealer:next.dealer,turn,events:[...s.events,event(`${actor.name} ${action.type==='HIT'?'hit':'stood'}.`)]};}
if(s.gameId==='solitaire'&&action.type==='DRAW'){if(s.stock.length){const [card,...rest]=s.stock;return{...s,stock:rest,waste:[...s.waste,card],events:[...s.events,event(`${actor.name} drew from the stock.`)]};}if(s.waste.length)return{...s,stock:[...s.waste].reverse(),waste:[],events:[...s.events,event('The waste returned to the stock.') ]};throw Error('The stock is empty');}
if(s.gameId==='highcard'&&action.type==='REVEAL'){s.revealedCards[actor.id]=true;s.players=s.players.map(p=>p.id===actor.id?{...p,revealed:true}:p);if(s.players.every(p=>s.revealedCards[p.id])){const winner=s.players.reduce((best,p)=>rankValue(p.hand[0].rank)>rankValue(best.hand[0].rank)?p:best,s.players[0]);return{...s,phase:'finished',winner:winner.id,events:[...s.events,event(`${winner.name} won the reveal.`,'win')]};}return{...s,turn:nextActive(s,s.turn),events:[...s.events,event(`${actor.name} revealed a card.`)]};}
if(s.gameId==='holdem'&&action.type==='CHECK'){s.checked[actor.id]=true;const all=s.players.every(p=>s.checked[p.id]);if(!all)return{...s,turn:nextActive(s,s.turn),events:[...s.events,event(`${actor.name} checked.`)]};const street=s.street==='preflop'?'flop':s.street==='flop'?'turn':s.street==='turn'?'river':'showdown';if(street==='showdown')return{...s,phase:'finished',street,events:[...s.events,event('The table reached showdown.','win')]};return{...s,street,checked:{},turn:0,events:[...s.events,event(`The ${street} was revealed.`,'deal')]};}
throw Error('Unsupported action for this game');}
export function projectRuntime(state:RuntimeState,viewerId:string):RuntimeState{const out=clone(state);const hidden={id:'hidden',rank:'?' as Card['rank'],suit:'?' as Card['suit']};if(state.gameId==='blackjack'&&out.dealer&&!out.dealer.revealed)out.dealer.hand=out.dealer.hand.map((card,index)=>index===0?card:hidden);out.players=out.players.map(p=>{const canSee=p.id===viewerId||state.gameId==='solitaire'||(state.gameId==='highcard'&&state.revealedCards[p.id]);return canSee?p:{...p,hand:p.hand.map(()=>hidden)};});if(state.gameId==='holdem'){const visible=state.street==='preflop'?0:state.street==='flop'?3:state.street==='turn'?4:5;out.community=state.community.slice(0,visible);}out.deck=[];return out;}
