import { Card, createDeck, shuffle } from '../../cards/deck';
export type Player = { id: string; name: string; hand: Card[]; removed: Card[]; correctGuesses: number; eliminatedAt?: number };
export type PendingQuestion = { askerId: string; targetId: string; question: string };
export type CardfallState = { phase: 'lobby'|'playing'|'finished'; players: Player[]; turn: number; cardsPerPlayer: number; events: { id: string; text: string; tone?: string }[]; ranking: string[]; pendingQuestion?: PendingQuestion };
export type Action = { type:'START'; seed?:number; cardsPerPlayer?:number } | {type:'GUESS'; actorId:string; targetId:string; cardId:string} | {type:'ASK'; actorId:string; targetId:string; question:string} | {type:'ANSWER'; actorId:string; yes:boolean};
const nextTurn = (s: CardfallState, idx: number) => { for(let n=1;n<=s.players.length;n++){const i=(idx+n)%s.players.length;if(s.players[i].hand.length>0)return i;} return idx; };
export function initial(players: Pick<Player,'id'|'name'>[]): CardfallState { return { phase:'lobby', players:players.map(p=>({...p,hand:[],removed:[],correctGuesses:0})), turn:0, cardsPerPlayer:5, events:[], ranking:[] }; }
export function reduce(state: CardfallState, action: Action): CardfallState {
 const s: CardfallState = structuredClone(state);
 if(action.type==='START'){ if(s.phase!=='lobby') throw Error('Game has already started'); if(s.players.length<2) throw Error('Need at least two players'); const n=action.cardsPerPlayer??5; if(n<1||n>10) throw Error('Cards per player must be 1-10'); if(s.players.length*n>52) throw Error('Not enough cards for this table'); const deck=shuffle(createDeck(),action.seed); s.cardsPerPlayer=n; s.players.forEach((p,i)=>{p.hand=deck.slice(i*n,(i+1)*n);}); s.phase='playing'; s.turn=0; s.events.push({id:crypto.randomUUID(),text:`The table dealt ${n} cards to each player.`,tone:'deal'}); return s; }
 if(s.phase!=='playing') throw Error('Game is not active'); const actor=s.players[s.turn];
 if(s.pendingQuestion && action.type!=='ANSWER') throw Error('Answer the pending question');
 if(action.type==='ASK'){if(action.actorId!==actor.id)throw Error('Not your turn'); const target=s.players.find(p=>p.id===action.targetId); if(!target||target.id===actor.id||target.hand.length===0)throw Error('Choose a player with cards'); if(!action.question.trim()||action.question.length>120)throw Error('Question must be 1-120 characters'); s.pendingQuestion={askerId:actor.id,targetId:target.id,question:action.question.trim()}; s.events.push({id:crypto.randomUUID(),text:`${actor.name} asked ${target.name}: “${action.question}”`}); s.turn=s.players.indexOf(target); return s;}
 if(action.type==='ANSWER'){const target=s.players[s.turn]; if(!s.pendingQuestion||s.pendingQuestion.targetId!==action.actorId||target.id!==action.actorId)throw Error('Only the selected target can answer'); s.events.push({id:crypto.randomUUID(),text:`${target.name} answered ${action.yes?'YES':'NO'}`,tone:action.yes?'yes':'no'}); delete s.pendingQuestion; s.turn=nextTurn(s,s.turn); return s;}
 if(action.type==='GUESS'){if(action.actorId!==actor.id)throw Error('Not your turn'); const target=s.players.find(p=>p.id===action.targetId); if(!target||target.id===actor.id)throw Error('Choose another player'); const index=target.hand.findIndex(c=>c.id===action.cardId); if(index<0){s.events.push({id:crypto.randomUUID(),text:`${actor.name} guessed wrong.`,tone:'miss'});s.turn=nextTurn(s,s.turn);return s;} const [card]=target.hand.splice(index,1); target.removed.push(card); actor.correctGuesses++; s.events.push({id:crypto.randomUUID(),text:`${actor.name} toppled a card from ${target.name}'s hand.`,tone:'hit'}); if(target.hand.length===0){target.eliminatedAt=s.events.length;s.ranking.push(target.id);s.events.push({id:crypto.randomUUID(),text:`${target.name} has been toppled from the table.`,tone:'out'});} const alive=s.players.filter(p=>p.hand.length); if(alive.length<=1){s.phase='finished'; if(alive[0])s.ranking.push(alive[0].id); s.events.push({id:crypto.randomUUID(),text:`${alive[0]?.name??'The table'} wins Cardfall.`,tone:'win'});} else s.turn=nextTurn(s,s.turn); return s; }
 return s;
}
