import { describe, expect, it } from 'vitest';
import { initial, reduce } from './engine';

describe('Cardfall',()=>{
 it('deals deterministic private hands',()=>{const s=reduce(initial([{id:'a',name:'A'},{id:'b',name:'B'}]),{type:'START',seed:1,cardsPerPlayer:5});expect(s.phase).toBe('playing');expect(s.players[0].hand).toHaveLength(5);expect(s.players[1].hand).toHaveLength(5);expect(new Set(s.players.flatMap(p=>p.hand.map(c=>c.id))).size).toBe(10);});
 it('rejects starting a game that is already active',()=>{const s=reduce(initial([{id:'a',name:'A'},{id:'b',name:'B'}]),{type:'START',seed:1,cardsPerPlayer:2});expect(()=>reduce(s,{type:'START',seed:2,cardsPerPlayer:2})).toThrow('Game has already started');});
 it('rejects a deal that exceeds the standard deck',()=>{const players=Array.from({length:8},(_,i)=>({id:String(i),name:`P${i}`}));expect(()=>reduce(initial(players),{type:'START',seed:1,cardsPerPlayer:7})).toThrow('Not enough cards');});
 it('removes a correctly guessed card without publishing its identity',()=>{let s=reduce(initial([{id:'a',name:'A'},{id:'b',name:'B'}]),{type:'START',seed:1,cardsPerPlayer:1});const card=s.players[1].hand[0];s=reduce(s,{type:'GUESS',actorId:'a',targetId:'b',cardId:card.id});expect(s.players[1].hand).toHaveLength(0);expect(s.players[0].correctGuesses).toBe(1);expect(s.events.at(-1)?.text).not.toContain(card.id);});
 it('adds a correctly guessed card to the public toppled pile',()=>{let s=reduce(initial([{id:'a',name:'A'},{id:'b',name:'B'}]),{type:'START',seed:1,cardsPerPlayer:1});const card=s.players[1].hand[0];s=reduce(s,{type:'GUESS',actorId:'a',targetId:'b',cardId:card.id});expect(s.toppledCards).toContainEqual(card);expect(s.lastTopple?.cardId).toBe(card.id);});
 it('emits structured question and answer metadata',()=>{let s=reduce(initial([{id:'a',name:'A'},{id:'b',name:'B'},{id:'c',name:'C'}]),{type:'START',seed:1,cardsPerPlayer:2});s=reduce(s,{type:'ASK',actorId:'a',targetId:'b',question:'Do you have a red card?'});const question=s.events.at(-1)!;expect(question.kind).toBe('question');expect(question.questionId).toBeTruthy();s=reduce(s,{type:'ANSWER',actorId:'b',yes:true});const answer=s.events.at(-1)!;expect(answer.kind).toBe('answer');expect(answer.questionId).toBe(question.questionId);expect(answer.answer).toBe(true);});
 it('stores a pending question and clears it after a yes/no answer',()=>{let s=reduce(initial([{id:'a',name:'A'},{id:'b',name:'B'}]),{type:'START',seed:1,cardsPerPlayer:2});s=reduce(s,{type:'ASK',actorId:'a',targetId:'b',question:'Do you have a heart?'});expect(s.pendingQuestion?.targetId).toBe('b');expect(s.pendingQuestion?.question).toContain('heart');s=reduce(s,{type:'ANSWER',actorId:'b',yes:true});expect(s.pendingQuestion).toBeUndefined();});
 it('rejects questions to players with no cards',()=>{let s=reduce(initial([{id:'a',name:'A'},{id:'b',name:'B'},{id:'c',name:'C'}]),{type:'START',seed:1,cardsPerPlayer:1});const card=s.players[1].hand[0];s=reduce(s,{type:'GUESS',actorId:'a',targetId:'b',cardId:card.id});expect(()=>reduce(s,{type:'ASK',actorId:'c',targetId:'b',question:'Are you still there?'})).toThrow('Choose a player with cards');});
 it('rejects a second action until the pending question is answered',()=>{let s=reduce(initial([{id:'a',name:'A'},{id:'b',name:'B'}]),{type:'START',seed:1,cardsPerPlayer:2});s=reduce(s,{type:'ASK',actorId:'a',targetId:'b',question:'Do you have a heart?'});expect(()=>reduce(s,{type:'ASK',actorId:'b',targetId:'a',question:'Can you answer me?'})).toThrow('Answer the pending question');expect(()=>reduce(s,{type:'GUESS',actorId:'b',targetId:'a',cardId:s.players[0].hand[0].id})).toThrow('Answer the pending question');expect(s.pendingQuestion?.targetId).toBe('b');});
});
