'use client';
import { useMemo, useState } from 'react';
import { createDeck } from '../lib/cards/deck';
import { initial, reduce, CardfallState } from '../lib/games/cardfall/engine';

const names=['You','Mara','Theo'];
export function TableView(){
 const [state,setState]=useState<CardfallState>(()=>initial(names.map((name,i)=>({id:String(i),name}))));
 const [question,setQuestion]=useState(''); const [target,setTarget]=useState('1'); const [guess,setGuess]=useState(''); const [tab,setTab]=useState<'ask'|'guess'>('ask');
 const me=state.players[0]; const active=state.players[state.turn]; const cards=createDeck();
 const play=(action:any)=>{try{setState(s=>reduce(s,action));}catch(e){alert((e as Error).message)}};
 const start=()=>play({type:'START',seed:17,cardsPerPlayer:5});
 const opponent=state.players.find(p=>p.id===target);
 return <div className="shell"><header className="topbar"><div className="brand"><span className="mark">✦</span><span>Card Table <b>Arena</b></span></div><div className="mode"><span className="live-dot"/> CARD<span className="muted">FALL</span><span className="divider"/> ROOM <strong>EMBER-7</strong></div><button className="ghost">Rules <span>?</span></button></header>
 <main className="arena"><div className="intro"><div><p className="eyebrow">A SOCIAL HIDDEN-CARD GAME</p><h1>Read the table.<br/><em>Topple the hand.</em></h1><p className="sub">Ask sharp questions. Make exact guesses.<br/>Leave no card standing.</p></div><div className="status-card"><span className="pulse"/><div><b>{state.phase==='lobby'?'Waiting to deal':'Game in progress'}</b><small>3 players · {state.cardsPerPlayer} cards each</small></div><span className="lock">♢</span></div></div>
 <section className="felt"><div className="felt-glow"/><div className="table-label"><span>ROUND {state.phase==='lobby'?'—':'01'}</span><span className="turn-label">{state.phase==='playing'?`${active.name.toUpperCase()}'S TURN`:'READY TO DEAL'}</span></div>
 {state.players.slice(1).map((p,i)=><div className={`seat seat-${i+1}`} key={p.id}><div className="seat-head"><span className="avatar">{p.name[0]}</span><div><b>{p.name}</b><small>{p.hand.length?`${p.hand.length} cards hidden`:'TOPPLED'}</small></div>{state.turn===state.players.indexOf(p)&&state.phase==='playing'&&<span className="your-turn">TURN</span>}</div><div className="back-row">{Array.from({length:Math.min(p.hand.length||5,5)}).map((_,j)=><div className="mini-back" key={j}>✦</div>)}</div></div>)}
 <div className="center-stack"><div className="table-ring"/><div className="discard"><span>✦</span><small>RESOLVED<br/>CARDS</small></div><div className="event-chip">{state.events.at(-1)?.text??'The table is quiet.'}</div></div>
 <div className="my-seat"><div className="my-head"><div className="avatar you">Y</div><div><b>You</b><small>{me.hand.length?`${me.hand.length} cards in hand`:'Toppled'}</small></div><span className="score">{me.correctGuesses} <small>TOPPLES</small></span></div><div className="hand">{me.hand.length?me.hand.map(c=><div className="playing-card" key={c.id}><small>{c.rank}</small><strong className={c.suit==='♥'||c.suit==='♦'?'red':''}>{c.suit}</strong></div>):<div className="empty-hand">Your hand is clear.</div>}</div></div></section>
 <section className="controls"><div className="control-head"><div><p className="eyebrow">YOUR MOVE</p><h2>{state.phase==='lobby'?'Deal the cards':active.id==='0'?'Make your play':'Watching the table'}</h2></div>{state.phase==='lobby'?<button className="primary" onClick={start}>Deal the cards <span>→</span></button>:state.phase==='finished'?<button className="primary" onClick={()=>setState(initial(names.map((name,i)=>({id:String(i),name}))))}>New game <span>↻</span></button>:<div className="tabs"><button className={tab==='ask'?'selected':''} onClick={()=>setTab('ask')}>Ask a question</button><button className={tab==='guess'?'selected':''} onClick={()=>setTab('guess')}>Guess a card</button></div>}</div>
 {state.phase==='playing'&&active.id==='0'&&<div className="action-panel">{tab==='ask'?<><label>Ask <select value={target} onChange={e=>setTarget(e.target.value)}>{state.players.filter(p=>p.id!=='0'&&p.hand.length).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select> something about their hand</label><div className="input-row"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="e.g. Do you have a red card?"/><button onClick={()=>{play({type:'ASK',actorId:'0',targetId:target,question});setQuestion('')}}>Ask <span>↗</span></button></div><p className="hint">They can only answer <b>YES</b> or <b>NO</b>. Questions are visible to everyone.</p></>:<><label>Guess a card in <select value={target} onChange={e=>setTarget(e.target.value)}>{state.players.filter(p=>p.id!=='0'&&p.hand.length).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select>’s hand</label><div className="input-row"><select value={guess} onChange={e=>setGuess(e.target.value)}><option value="">Choose a card…</option>{cards.map(c=><option value={c.id} key={c.id}>{c.rank}{c.suit}</option>)}</select><button onClick={()=>{if(guess)play({type:'GUESS',actorId:'0',targetId:target,cardId:guess});setGuess('')}}>Make guess <span>↗</span></button></div><p className="hint">Correct guesses topple a card and send it to the resolved pile.</p></>}</div>}
 {state.phase==='playing'&&active.id!=='0'&&<div className="waiting">{active.name} is thinking. Watch the table activity below.</div>}
 <div className="log">{state.events.slice(-4).reverse().map(e=><div className={`log-item ${e.tone||''}`} key={e.id}><span className="log-dot"/><span>{e.text}</span></div>)}</div></section></main><footer><span>PLAY MONEY · JUST FOR FUN</span><span>Cardfall 01 <i/> No account required</span></footer></div>
}
