import { Card, createDeck, shuffle } from '../../cards/deck';
export type BlackjackHand={hand:Card[];stood:boolean;};
export type BlackjackState={phase:'playing'|'finished';players:Record<string,BlackjackHand>;dealer:{hand:Card[];revealed:boolean};deck:Card[];results?:Record<string,'win'|'lose'|'push'>};
export function handValue(hand:Card[]){let total=0,aces=0;for(const c of hand){if(c.rank==='A'){aces++;total+=11}else if(['K','Q','J'].includes(c.rank))total+=10;else total+=Number(c.rank)}while(total>21&&aces--)total-=10;return total}
export function createBlackjack(ids:string[],seed=1):BlackjackState{if(ids.length<1||ids.length>5)throw Error('Blackjack supports 1-5 players');const d=shuffle(createDeck(),seed);const players:Record<string,BlackjackHand>={};ids.forEach((id,i)=>players[id]={hand:[d[i],d[i+ids.length]],stood:false});const used=ids.length*2;return{phase:'playing',players,dealer:{hand:[d[used],d[used+1]],revealed:false},deck:d.slice(used+2)}}
function settleIfReady(s:BlackjackState):BlackjackState{if(!Object.values(s.players).every(p=>p.stood||handValue(p.hand)>21))return s;const deck=[...s.deck];const dealer={...s.dealer, revealed:true, hand:[...s.dealer.hand]};while(handValue(dealer.hand)<17&&deck.length){dealer.hand.push(deck.shift()!)}const dv=handValue(dealer.hand);const results:Record<string,'win'|'lose'|'push'>={};for(const [id,p] of Object.entries(s.players)){const pv=handValue(p.hand);results[id]=pv>21||dv<=21&&dv>pv?'lose':dv>21||pv>dv?'win':'push'}return{...s,phase:'finished',dealer,deck,results}}
export function hit(s:BlackjackState,id:string){if(s.phase!=='playing')throw Error('Round is not active');const p=s.players[id];if(!p||p.stood)throw Error('Invalid player');const [card,...deck]=s.deck;if(!card)throw Error('Deck exhausted');const next:BlackjackState={...s,players:{...s.players,[id]:{...p,hand:[...p.hand,card],stood:handValue([...p.hand,card])>=21}},deck};return settleIfReady(next)}
export function stand(s:BlackjackState,id:string){if(s.phase!=='playing')throw Error('Round is not active');const p=s.players[id];if(!p||p.stood)throw Error('Invalid player');return settleIfReady({...s,players:{...s.players,[id]:{...p,stood:true}}})}
export function settle(s:BlackjackState){return settleIfReady({...s,players:Object.fromEntries(Object.entries(s.players).map(([id,p])=>[id,{...p,stood:true}]))})}
